---

- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - htop
  - sudo
  - fail2ban
  - ufw
  - zabbix-agent
  - unattended-upgrades

- name: add ssh-user group
  group: name=ssh-user state=present

- name: add ansible user
  user: name=ansible state=present groups=sudo,ssh-user createhome=yes home=/home/ansible system=yes

- name: add ansible key
  authorized_key: user=ansible state=present key="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEale3rgwFlUeyFUCGtSFnYC0gHJpl1+qFv0hmy+hU/C ansible"

- name: set static ip
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644

- name: set hostname
  hostname: name={{ hostname }}

- name: configure ufw firewall
  ufw: state=enabled policy=deny rule=allow src={{ item }}
  with_items:
  - 127.0.0.0/8 # not really private but w/e
  - 128.153.144.0/23
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16

- name: copy ssh configs
  copy: src=sshd_config dest=/etc/ssh/sshd_config mode="u=rw,g=r,o=r" owner=root group=root
  copy: src=ssh_config dest=/etc/ssh/ssh_config mode="u=rw,g=r,o=r" owner=root group=root
